/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UiKitRouteImport } from './routes/ui-kit'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PatientRouteRouteImport } from './routes/patient/route'
import { Route as DoctorsRouteRouteImport } from './routes/doctors/route'
import { Route as DoctorRouteRouteImport } from './routes/doctor/route'
import { Route as ClinicsRouteRouteImport } from './routes/clinics/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoctorsIndexRouteImport } from './routes/doctors/index'
import { Route as ClinicsIndexRouteImport } from './routes/clinics/index'
import { Route as DoctorAvailabilityRouteImport } from './routes/doctor/availability'
import { Route as DoctorAppointmentsRouteImport } from './routes/doctor/appointments'
import { Route as DoctorAgendaRouteImport } from './routes/doctor/agenda'
import { Route as ClinicsClinicIdRouteImport } from './routes/clinics/$clinicId'
import { Route as PatientAppointmentsRouteRouteImport } from './routes/patient/appointments/route'
import { Route as DoctorsDoctorIdRouteRouteImport } from './routes/doctors/$doctorId/route'
import { Route as PatientAppointmentsIndexRouteImport } from './routes/patient/appointments/index'
import { Route as DoctorsDoctorIdIndexRouteImport } from './routes/doctors/$doctorId/index'
import { Route as PatientAppointmentsAppointmentIdRouteImport } from './routes/patient/appointments/$appointmentId'
import { Route as DoctorsDoctorIdBookRouteImport } from './routes/doctors/$doctorId/book'

const UiKitRoute = UiKitRouteImport.update({
  id: '/ui-kit',
  path: '/ui-kit',
  getParentRoute: () => rootRouteImport,
})
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
})
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
})
const PatientRouteRoute = PatientRouteRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
})
const DoctorsRouteRoute = DoctorsRouteRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
})
const DoctorRouteRoute = DoctorRouteRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
})
const ClinicsRouteRoute = ClinicsRouteRouteImport.update({
  id: '/clinics',
  path: '/clinics',
  getParentRoute: () => rootRouteImport,
})
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
})
const DoctorsIndexRoute = DoctorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorsRouteRoute,
})
const ClinicsIndexRoute = ClinicsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClinicsRouteRoute,
})
const DoctorAvailabilityRoute = DoctorAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => DoctorRouteRoute,
})
const DoctorAppointmentsRoute = DoctorAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => DoctorRouteRoute,
})
const DoctorAgendaRoute = DoctorAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => DoctorRouteRoute,
})
const ClinicsClinicIdRoute = ClinicsClinicIdRouteImport.update({
  id: '/$clinicId',
  path: '/$clinicId',
  getParentRoute: () => ClinicsRouteRoute,
})
const PatientAppointmentsRouteRoute =
  PatientAppointmentsRouteRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => PatientRouteRoute,
  })
const DoctorsDoctorIdRouteRoute = DoctorsDoctorIdRouteRouteImport.update({
  id: '/$doctorId',
  path: '/$doctorId',
  getParentRoute: () => DoctorsRouteRoute,
})
const PatientAppointmentsIndexRoute =
  PatientAppointmentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PatientAppointmentsRouteRoute,
  })
const DoctorsDoctorIdIndexRoute = DoctorsDoctorIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorsDoctorIdRouteRoute,
})
const PatientAppointmentsAppointmentIdRoute =
  PatientAppointmentsAppointmentIdRouteImport.update({
    id: '/$appointmentId',
    path: '/$appointmentId',
    getParentRoute: () => PatientAppointmentsRouteRoute,
  })
const DoctorsDoctorIdBookRoute = DoctorsDoctorIdBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => DoctorsDoctorIdRouteRoute,
})

const ClinicsRouteRouteChildren = {
  ClinicsClinicIdRoute: ClinicsClinicIdRoute,
  ClinicsIndexRoute: ClinicsIndexRoute,
}

const ClinicsRouteRouteWithChildren = ClinicsRouteRoute._addFileChildren(
  ClinicsRouteRouteChildren,
)

const DoctorRouteRouteChildren = {
  DoctorAgendaRoute: DoctorAgendaRoute,
  DoctorAppointmentsRoute: DoctorAppointmentsRoute,
  DoctorAvailabilityRoute: DoctorAvailabilityRoute,
}

const DoctorRouteRouteWithChildren = DoctorRouteRoute._addFileChildren(
  DoctorRouteRouteChildren,
)

const DoctorsDoctorIdRouteRouteChildren = {
  DoctorsDoctorIdBookRoute: DoctorsDoctorIdBookRoute,
  DoctorsDoctorIdIndexRoute: DoctorsDoctorIdIndexRoute,
}

const DoctorsDoctorIdRouteRouteWithChildren =
  DoctorsDoctorIdRouteRoute._addFileChildren(DoctorsDoctorIdRouteRouteChildren)

const DoctorsRouteRouteChildren = {
  DoctorsDoctorIdRouteRoute: DoctorsDoctorIdRouteRouteWithChildren,
  DoctorsIndexRoute: DoctorsIndexRoute,
}

const DoctorsRouteRouteWithChildren = DoctorsRouteRoute._addFileChildren(
  DoctorsRouteRouteChildren,
)

const PatientAppointmentsRouteRouteChildren = {
  PatientAppointmentsAppointmentIdRoute: PatientAppointmentsAppointmentIdRoute,
  PatientAppointmentsIndexRoute: PatientAppointmentsIndexRoute,
}

const PatientAppointmentsRouteRouteWithChildren =
  PatientAppointmentsRouteRoute._addFileChildren(
    PatientAppointmentsRouteRouteChildren,
  )

const PatientRouteRouteChildren = {
  PatientAppointmentsRouteRoute: PatientAppointmentsRouteRouteWithChildren,
}

const PatientRouteRouteWithChildren = PatientRouteRoute._addFileChildren(
  PatientRouteRouteChildren,
)

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  ClinicsRouteRoute: ClinicsRouteRouteWithChildren,
  DoctorRouteRoute: DoctorRouteRouteWithChildren,
  DoctorsRouteRoute: DoctorsRouteRouteWithChildren,
  PatientRouteRoute: PatientRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  UiKitRoute: UiKitRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
